/**
 * The words of Settings → SDC Anywhere (0.17), in English - `strings.anywhere`. The language packs in
 * `locales/` translate them like any other part; what a pack leaves out is shown in English.
 */
export const anywhereStrings = {
  title: 'SDC Anywhere',
  intro:
    'Control this computer’s SDC from any browser, with nothing to install. Your files stay here; the relay only carries encrypted messages it cannot read. It is off until you turn it on.',
  on: 'On',
  off: 'Off',
  enable: 'Turn on',
  disable: 'Turn off',
  enabledToast: 'SDC Anywhere is on',
  disabledToast: 'SDC Anywhere is off',
  failed: 'SDC Anywhere could not be changed',
  badge: {
    label: 'Anywhere',
    waiting: (n: number): string => `Anywhere · ${n} waiting`,
    titleConnected: 'SDC Anywhere is on and connected',
    titleConnecting: 'SDC Anywhere is on and connecting to the relay',
  },
  link: {
    connected: 'Connected to the relay',
    connecting: 'Connecting to the relay…',
    off: 'Not running',
    error: (why: string): string => `The relay link failed: ${why}`,
  },
  browsers: (n: number): string => (n === 1 ? '1 browser connected' : `${n} browsers connected`),
  waiting: (n: number): string => (n === 1 ? '1 request is waiting' : `${n} requests are waiting`),
  keys: {
    title: 'Where the identity key is kept',
    os: 'Your operating system’s keychain.',
    file: 'A protected file in SDC’s folder (this computer has no keychain SDC can reach).',
    accept: 'Keep the key in a protected file',
    acceptHelp: 'Needed to turn SDC Anywhere on here. A file is less safe than a keychain: anything that can read your user folder can read it.',
  },
  devices: {
    title: 'Devices',
    none: 'No device is paired yet.',
    add: 'Add a device',
    addGuest: 'Add a guest session',
    guest: 'Guest',
    revoked: 'Revoked',
    lastSeen: (when: string): string => `last used ${when}`,
    never: 'never used',
    revoke: 'Revoke',
    revoked_toast: 'Device revoked',
  },
  pair: {
    title: 'Pair a device',
    scan: 'Scan this code with the phone, or open the link on the device.',
    expires: (minutes: number): string => `Valid for ${minutes} minutes, once.`,
    fingerprint: 'This computer’s fingerprint',
    copy: 'Copy link',
    copied: 'Link copied',
    close: 'Close',
    request: (name: string): string => `“${name}” wants to pair`,
    compare: 'Confirm only if the phone shows the same six digits:',
    accept: 'The digits match: pair it',
    decline: 'Not me: decline',
  },
  settings: {
    title: 'How it behaves',
    notifyWhen: 'Tell my phone about a request',
    notifyOptions: { idle: 'only when I am away from the keyboard', always: 'always', never: 'never' },
    onTimeout: 'When nobody answers a request',
    onTimeoutOptions: { pause: 'leave the work waiting', deny: 'refuse it' },
    timeout: 'A request waits (minutes)',
    viewLock: 'Lock the browser view after (minutes of no use)',
    operate: 'Allowing window (minutes)',
    guest: 'A guest session lasts at most (minutes)',
    email: 'Email for requests and sign-in links',
    emailPlaceholder: 'you@example.com',
    emailHelp:
      'If nobody answers a request for a minute, one email goes out with a link and no details. The same address lets you add a new browser with a one-time link; you still approve that browser here. Leave it empty to turn email off.',
    escalate: 'Send that email after (seconds without an answer)',
    saved: 'Saved',
    note: 'These can be made stricter than the defaults but not looser. They apply the next time SDC Anywhere starts.',
  },
  danger: {
    title: 'Reset',
    reset: 'Reset this computer’s identity',
    resetHelp: 'Every paired device must pair again. Use it if you think the key was copied.',
    resetConfirm: 'Reset the identity? All paired devices stop working until they pair again.',
    resetDone: 'Identity reset. SDC Anywhere is off.',
  },
} as const;
