/**
 * The words of the Trust Kernel's, the Intent Engine's and the agency's surfaces (0.12), in English -
 * `strings.kernel`. Kept in their own file for size; `strings.ts` includes them, and the language packs in
 * `locales/` translate them like any other part of `strings`.
 */
export const kernelStrings = {
  kill: {
    label: 'Stop all',
    title: 'Kill switch: stop every running turn, check, deploy and command now (Ctrl Shift .)',
    /** `processes` (0.16.0): a dev server or a command the agent left running is work too - the toast said
        "Nothing was running" right after stopping one. */
    done: (stopped: number, checkpoints: number, processes = 0): string =>
      stopped + processes === 0
        ? 'Nothing was running. The kill switch is ready.'
        : [
            stopped === 0 ? '' : `Stopped ${stopped} running task${stopped === 1 ? '' : 's'}.`,
            processes === 0 ? '' : `Stopped ${processes} running process${processes === 1 ? '' : 'es'}.`,
            checkpoints === 0 ? '' : `${checkpoints} checkpoint${checkpoints === 1 ? '' : 's'} keep the state they stopped in.`,
          ]
            .filter((part) => part !== '')
            .join(' '),
    failed: 'The kill switch could not reach the daemon',
  },

  /** A stopped turn's chip on its footer; the whole sentence is the turn's ending and the chip's title. */
  stop: {
    budget: 'Stopped: budget',
    runaway: 'Stopped: loop guard',
  },

  cost: {
    meter:(today: string): string => `${today} today`,
    meterTurn: (estimate: string): string => `turn ≈${estimate} est.`,
    meterTitle: 'AI spend today - open the Cost center',
    title: 'Cost center',
    subtitle: 'What AI has cost, the budgets that stop it overspending, and what was saved - measured, never guessed.',
    loading: 'Reading the ledger of turns…',
    today: 'Today',
    month: 'This month',
    saved: 'Saved',
    noBaseline: 'Choose a baseline model below to measure savings.',
    savedNote: (turns: number): string => `against your baseline, over ${turns} measured turn${turns === 1 ? '' : 's'}`,
    measured: 'Measured turns',
    measuredNote: 'the rest ran on a subscription or reported no tokens',
    byDay: 'By day',
    none: 'Nothing spent yet.',
    byModel: 'By model',
    model: 'Model',
    turns: 'Turns',
    tokens: 'Tokens in / out',
    spend: 'Spend',
    byProject: 'By project and site',
    budgets: 'Budgets',
    budgetsNote: 'A turn that would start over a budget is refused with the reason; a turn that crosses its per-turn budget while running is stopped. Empty means no limit.',
    budget: { turn: 'Per turn ($)', chat: 'Per chat ($)', day: 'Per day ($)', month: 'Per month ($)' },
    noLimit: 'no limit',
    baseline: 'Baseline model for "saved" (the same measured tokens priced on it)',
    noBaselineOption: 'No baseline - do not claim savings',
    save: 'Save budgets',
    savedToast: 'Budgets saved',
    failed: 'The cost ledger could not be read',
    source: {
      measured: 'Measured: the provider reported this cost',
      priced: 'Priced: the provider reported the tokens; the price is the catalogue’s',
      local: 'Local model: no cost',
      subscription: 'Subscription: no per-turn charge',
      unpriced: 'The catalogue has no price for this model',
      none: 'No usage was reported',
    },
    sourceShort: {
      measured: 'measured',
      priced: 'priced',
      local: 'local',
      subscription: 'subscription',
      unpriced: 'unpriced',
      none: 'not reported',
    },
  },

  trust: {
    chip: (score: number, level: string): string => `Trust ${score} · ${level}`,
    level: { high: 'high', medium: 'medium', low: 'low' },
  },

  policy: {
    title: 'Policy',
    open: 'Edit the policy for this chat’s folder',
    noFolder: 'This chat has no folder yet, so it has no policy file. Open a folder first.',
    noChat: 'Open a chat to see its folder’s policy.',
    loading: 'Reading the policy…',
    fromFile: 'This folder has its own .sdc/policy.toml; SDC’s defaults apply underneath it.',
    defaults: 'This folder has no policy file yet: SDC’s defaults apply. Saving writes .sdc/policy.toml.',
    rawHint: 'The file itself. It is checked before it is saved: a file that does not parse is refused, not written.',
    production: 'Production',
    productionHelp: 'Auto mode runs as Pro here (commands wait for you), and deploys can require an approval.',
    privacy: 'Private: local models only',
    privacyHelp: 'This code never leaves the machine: only an Ollama model may read it.',
    autoRollback: 'The Night Guardian may roll back on its own',
    autoRollbackHelp: 'Only ever to the last good deploy; a fix always waits for approval.',
    maxFiles: 'Most files one turn may change (blast radius)',
    maxTurnUsd: 'Most one turn may cost ($)',
    lists: { protectedPaths: 'More protected paths', alwaysAsk: 'More commands that always ask', denyCommands: 'Commands that are refused' },
    listHelp: {
      protectedPaths: 'One pattern per line (config/*.yml, secrets/**). An AI asks before touching them, in every mode.',
      alwaysAsk: 'One per line. Matching commands wait for you even in Auto.',
      denyCommands: 'One per line. A matching command is refused outright.',
    },
    alwaysOn: (list: string): string => `Always protected: ${list}.`,
    editText: 'Edit as text',
    editForm: 'Back to the form',
    ledgerTitle: 'Audit ledger',
    ledgerHelp: 'Every action every AI took is recorded in a hash chain; a row edited or removed afterwards breaks the chain at that row.',
    verifyLedger: 'Check the chain',
    violations: 'Recent policy hits',
    close: 'Close',
    save: 'Save policy',
    loadFailed: 'The policy could not be read',
    saveFailed: 'The policy could not be saved',
  },

  audit: { failed: 'The audit ledger could not be read' },

  timeline: {
    labelFailed: 'The label could not be saved',
    filesFailed: 'The checkpoint’s files could not be read',
    restoreFailed: 'The file could not be restored',
    restored: (path: string, outcome: string): string =>
      outcome === 'removed' ? `${path} did not exist at that checkpoint, so it was removed. Undo is in the Time Machine.` : `${path} is back as it was. Undo is in the Time Machine.`,
    branchesFailed: 'The timeline’s branches could not be read',
    irreversible: (reason: string): string => `A rewind cannot undo everything after this: ${reason}`,
    labelInput: 'Checkpoint label',
    rewind: 'Rewind here',
    compare: 'Compare',
    label: 'Label',
    loading: 'Reading what changed…',
    noChanges: 'Nothing has changed since this checkpoint.',
    status: { A: 'added since', M: 'changed since', D: 'deleted since', R: 'renamed since' },
    restoreFileTitle: (path: string): string => `Put ${path} back as it was at this checkpoint (the rest of the folder stays as it is)`,
    restoreFile: 'Restore this file',
    branches: 'Branches',
    savedPresent: 'The state before a switch',
    branchMeta: (checkpoints: number, turns: number, at: string): string => `${checkpoints} checkpoint(s) · ${turns} turn(s) · ${at.slice(0, 16).replace('T', ' ')}`,
    switchTo: 'Switch to',
  },

  proof: {
    open: 'Open the Proof panel',
    empty: 'Proof appears here once this chat has a turn: what it changed, how it was checked, its Trust score, cost and rollback point.',
    turn: 'Turn',
    trust: 'Trust score',
    noScore: 'Scored when the turn ends.',
    changed: (count: number): string => `Changed files (${count})`,
    nothing: 'None.',
    commands: (count: number): string => `Commands (${count})`,
    verification: 'Verification',
    unverified: 'Not verified yet - nothing has proved this change.',
    verifyNow: 'Verify this turn',
    verdict: {
      PASS: 'PASS - checks ran and passed, scans are clean',
      FAIL: 'FAIL - see what failed below',
      NO_CHECKS: 'NO CHECKS - nothing to run and nothing changed',
      UNPROVEN: 'UNPROVEN - nothing failed, but no test proved it',
    },
    scans: (secrets: number, sast: number): string => `Secrets found: ${secrets} · risky code patterns: ${sast}`,
    depsUnchecked: 'dependencies not checked',
    deps: (count: number): string => `high/critical dependency advisories: ${count}`,
    review: (model: string, verdict: string): string => `Second AI (${model}): ${verdict}`,
    cost: 'Cost',
    noCost: 'Reported when the turn ends.',
    estimateOnly: (usd: string): string => `Estimated ${usd} before it ran`,
    tokens: (input: number, output: number): string => `${input} in / ${output} out`,
    estimateWas: (usd: string): string => `estimated ${usd}`,
    notMeasured: 'not a measured number',
    rollback: 'Rollback point',
    noChangeNoCheckpoint: 'Nothing changed, so there is nothing to roll back.',
    noCheckpoint: 'No checkpoint was recorded for this turn.',
    rewind: 'Rewind to before this turn',
    ledger: 'Audit trail',
    showLedger: 'Show the ledger rows',
    intact: (entries: number): string => `Ledger intact - ${entries} rows, nobody has edited them`,
    broken: (row: number): string => `Ledger BROKEN at row ${row} - something was changed after it was written`,
    export: 'Export Proof Pack',
    failed: 'The proof could not be built',
  },

  intent: {
    title: 'What SDC understood',
    reading: 'Reading your request…',
    readAs: (label: string): string => `Read as ${label}`,
    dialect: (dialect: string): string => dialect,
    romanized: 'romanized',
    mixed: 'mixed languages',
    source: { model: 'read by AI', heuristic: 'offline reading - please check', person: 'your edit' },
    risk: { low: 'low risk', medium: 'medium risk', high: 'high risk' },
    overall: 'overall',
    confidence: (percent: number): string => `${percent}%`,
    confidenceLabel: 'How sure SDC is that this is what you meant',
    backTitle: 'In your words - is this right?',
    target: 'Where',
    goal: 'What you want',
    unsure: 'unsure',
    sure: 'sure',
    conditions: 'Done means',
    conditionLabel: (index: number): string => `Condition ${index}`,
    addCondition: 'Add a condition…',
    outOfScope: 'Will not touch',
    questions: 'One thing to check',
    answer: 'Your answer',
    glossaryTitle: 'Teach SDC a word',
    term: 'word',
    meaning: 'means',
    addTerm: 'Add',
    showPrompt: 'See the compiled prompt',
    hidePrompt: 'Hide the compiled prompt',
    compiledNote: (engine: string): string => `As SDC would send it to ${engine} (from the reading before your edits).`,
    confirm: 'Confirm and run',
    asTyped: 'Run as typed',
    cancel: 'Cancel',
    shortcut: 'Ctrl Enter confirms · Esc cancels',
    failed: 'The request could not be read',
  },

  language: {
    title: 'Language',
    desc: 'The window’s language, how answers come back, and the words SDC has learned from you.',
    ui: 'Window language',
    uiHelp: 'Switching reloads the window. Alerts, Proof Packs and client pages use it too.',
    contract: 'Confirm what SDC understood',
    contractHelp: 'Off by default: Enter starts the work at once. On, a card shows the reading first and waits for your yes.',
    contractMode: { auto: 'When it matters', always: 'Always', off: 'Never' },
    style: 'Answers in a regional form',
    styleHelp: 'When you write in a dialect, answer in it - or in the standard form of the language.',
    styleStandard: 'Standard form',
    styleDialect: 'The same dialect',
    code: 'Code, comments, commits',
    codeHelp: 'Always in the project’s own language, English by default.',
    voice: 'Voice input',
    voiceUnknown: 'The daemon has not said yet.',
    voiceLocal: (program: string): string => `Transcribed on this machine by ${program}.`,
    voiceOnline: (providers: string): string => `No local transcriber: uses ${providers}, and says so each time.`,
    voiceNone: 'No transcriber is available.',
    ready: 'ready',
    notReady: 'not set up',
    glossary: 'Glossary',
    glossaryHelp: (scope: string): string => `Words you taught SDC (${scope === 'global' ? 'every project' : scope.replace('project:', '')}). The next reading uses them.`,
    forget: 'Forget',
    glossaryFailed: 'The glossary could not be read',
  },

  voice: {
    start: 'Speak (voice input)',
    stop: 'Stop and transcribe',
    heardLocally: (engine: string): string => `Heard on this machine (${engine})`,
    heardOnline: (engine: string): string => `Heard by ${engine} (your recording left this machine)`,
    nothing: 'Nothing was heard in that recording.',
    noMicrophone: 'The microphone could not be opened.',
    failed: 'The recording could not be transcribed',
  },

  agency: {
    title: 'Agency',
    failed: 'The agency request failed',
    awaitingApproval: 'This deploy waits for an approval (Agency → Approvals).',
    tabs: { sites: 'Sites', deploys: 'Deploys', approvals: 'Approvals', playbooks: 'Playbooks', xray: 'Takeover X-ray', guardian: 'Night Guardian' },
    loading: 'Loading…',
    sitesHelp: 'Every site SDC ships and watches: health, backups, the Ops score, and one-click actions.',
    addSite: 'Add a site',
    noSites: 'No sites yet. Add one: a folder on a machine that serves something at a URL.',
    deploy: 'Safe deploy',
    checkHealth: 'Check health',
    sendForApproval: 'Staging + client approval',
    rehearse: 'Rehearse a migration',
    edit: 'Edit',
    remove: 'Remove',
    deployState: { running: 'running', success: 'deployed', failed: 'failed', rolled_back: 'rolled back', rollback_failed: 'rollback failed', awaiting_approval: 'awaiting approval' },
    stepState: { pending: 'waiting', running: 'running', pass: 'passed', fail: 'failed', skipped: 'skipped' },
    form: {
      name: 'Name',
      host: 'Machine',
      root: 'Folder',
      url: 'URL',
      detect: 'Detect from the folder',
      steps: 'Deploy steps (one command per line)',
      stepsHelp: 'Run in the site’s folder, after a mandatory backup. Any failure rolls the files back.',
      restart: 'Restart command',
      backupDir: 'Backup folder',
      dbKind: 'Database',
      db: { none: 'None', wordpress: 'WordPress (read from wp-config.php)', mysql: 'MySQL / MariaDB', postgres: 'PostgreSQL' },
      dbName: 'Database name',
      healthText: 'Health: the page must contain',
      logFile: 'Error log to watch',
      stagingUrl: 'Staging URL (optional)',
      stagingDb: 'Staging database (WordPress)',
      production: 'Production',
      requireApproval: 'Deploys need an approval',
      watch: 'Watch its health',
      save: 'Save',
      cancel: 'Cancel',
    },
    health: {
      notChecked: 'Not checked yet.',
      up: 'up',
      down: 'down',
      unknown: 'no URL',
      ssl: (days: number): string => `SSL ${days}d`,
      disk: (percent: number): string => `disk ${percent}%`,
      noBackup: 'no backup',
      backup: (hours: number): string => `backup ${hours}h old`,
      errors: (count: number): string => `${count} log errors`,
      ops: (score: number, level: string): string => `Ops score ${score} · ${level}`,
      level: { healthy: 'healthy', watch: 'watch', 'at-risk': 'at risk' },
    },
    staging: {
      help: 'A copy of the site on the same server, and a page in the client’s language where they approve it. The real site does not change.',
      summary: 'What changed, for the client',
      changes: 'The changes, one per line',
      language: 'Client’s language',
      create: 'Make the copy and the page',
      stop: 'Stop the copy',
      state: { copying: 'Copying the site…', ready: 'Ready - send the client this page:', failed: 'The staging copy failed.' },
      noPhp: 'This server has no PHP, so the page’s buttons open an email to you instead of recording the answer.',
    },
    shadow: {
      help: 'The migration runs on a throwaway copy of the real database first; the real one is only read. Use {db} for the copy’s name.',
      run: 'Rehearse',
      running: 'Copying the database and running the migration on the copy…',
    },
    noDeploys: 'No deploys yet.',
    backupAt: (files: string, db: string): string => `Backup: files ${files} · database ${db}`,
    undoPreview: 'Undo preview',
    rollback: 'Roll back to before this',
    fixWithAi: 'Fix with AI',
    fixPrompt: (step: string, log: string): string =>
      `The deploy step "${step}" failed. Find the cause in this site's folder and fix it. Do not deploy: I will ship it with Safe Deploy after Verify.\n\nThe step's output:\n${log}`,
    previewTitle: (count: number): string => `A rollback would change ${count} file(s)`,
    change: { added: 'remove (added by the deploy):', modified: 'restore:', deleted: 'bring back:' },
    dbRestoreHelp: 'Restoring the database replaces every row written since the backup. Type RESTORE to confirm.',
    restoreDb: 'Restore the database',
    noApprovals: 'Nothing waits for an approval.',
    approvalState: { pending: 'waiting', approved: 'approved', declined: 'declined', question: 'question', used: 'used' },
    approvalKind: { deploy: 'Production deploy', client: 'Client sign-off', 'guardian-fix': 'Night Guardian fix', general: 'Approval' },
    requestedBy: (who: string): string => `asked by ${who}`,
    checkAnswer: 'Check the client’s answer',
    openFix: 'Open the prepared fix in a chat',
    approve: 'Approve',
    decline: 'Decline',
    playbooksHelp: 'The same steps on many sites. Each site gets its own backup, health check and rollback.',
    onSites: 'Run on',
    stepCount: (count: number): string => `${count} step(s)`,
    run: 'Run',
    playbookStarted: (count: number): string => `Started on ${count} site(s) - follow them under Deploys.`,
    newPlaybook: 'New playbook',
    playbookStepsHint: 'one step per line - a command, or "ai: " and a request',
    xray: {
      noHosts: 'Add a VPS first: X-ray scans a server.',
      help: 'A read-only scan of a server you inherited: nothing is installed or changed. You get a map, a handover document and the risks, ranked.',
      scan: 'Scan',
      scanning: 'Scanning (read-only)…',
      scannedAt: (at: string): string => `scanned ${at}`,
      risks: (count: number): string => `Risks (${count})`,
      level: { critical: 'critical', high: 'high', medium: 'medium', low: 'low' },
      fix: (fix: string): string => `Fix: ${fix}`,
      section: {
        sites: 'Sites',
        wordpress: 'WordPress installs',
        databases: 'Databases',
        services: 'Services',
        cron: 'Scheduled jobs',
        docker: 'Containers',
        ports: 'Open ports',
        runtimes: 'Runtimes',
        certificates: 'Certificates',
        backups: 'Backups',
      },
      none: 'none found',
    },
    guardian: {
      help: 'When a watched site stays down, the Night Guardian can roll it back to the last good deploy - and nothing else. A fix is prepared and waits for your approval.',
      watch: 'Guard this site',
      autoRollback: 'May roll back on its own',
      log: 'What happened',
      quiet: 'All quiet.',
    },
  },

  team: {
    title: 'Team',
    desc: 'Who is at this desk, and what their role lets them do.',
    localNote:
      'Roles are enforced by the daemon on this machine. A team on several machines needs a shared server, which SDC does not run - the roles here are the rules it would enforce.',
    atDesk: 'At the desk now',
    role: (role: string): string => `Your role: ${role}`,
    nobody: '(nobody - full owner access)',
    roles: { owner: 'Owner', developer: 'Developer', reviewer: 'Reviewer', client: 'Client (read-only)' },
    roleHelp: {
      owner: 'everything, including the team, the policy and the budgets.',
      developer: 'chats, files, commands, staging and deploys that need no approval.',
      reviewer: 'reads everything, runs Verify, approves or declines.',
      client: 'reads sites, health and proof, and answers their own sign-off.',
    },
    remove: 'Remove',
    name: 'Name',
    add: 'Add',
    save: 'Save the team',
    email: 'Agency email',
    emailHelp: 'Where a client page’s buttons send the answer when the server has no PHP.',
    styleGuide: 'Agency style guide',
    styleGuideHelp: 'How your agency writes code. Every compiled prompt carries it - per project memory stays per project.',
    failed: 'The team could not be read',
  },

  updates: {
    title: 'Updates and diagnostics',
    desc: 'The release channel, the version to roll back to, crash reports and the CLIs.',
    channel: 'Channel',
    channelHelp: 'Stable is the newest full release; Beta also takes pre-releases.',
    stable: 'Stable',
    beta: 'Beta',
    check: 'Check for updates',
    available: (tag: string, current: string): string => `${tag} is available (you have ${current}).`,
    upToDate: (current: string): string => `You have the newest release (${current}).`,
    download: (tag: string): string => `Download ${tag}`,
    rollback: (tag: string): string => `If an update misbehaves, the previous release is ${tag}.`,
    openRelease: 'Open it',
    lowBandwidth: 'Low-bandwidth mode',
    lowBandwidthHelp: 'Fewer, larger updates while a turn streams, and no live thinking - for a slow link.',
    phone: 'Status page for your phone',
    phoneHelp: 'A read-only page on your local network: running work, site health, spend. Off by default.',
    selfCheck: 'Coding CLIs',
    crashes: 'Crash reports',
    crashesHelp: 'Kept on this machine only. Sending one opens a GitHub issue you can read and edit first.',
    noCrashes: 'No crashes recorded.',
    send: 'Send as an issue…',
    clear: 'Clear the reports',
    failed: 'The update check failed',
  },

  onboarding: {
    title: 'Welcome to SDC',
    progress: 'Setup progress',
    stepOf: (step: number, total: number, label: string): string => `Step ${step} of ${total}: ${label}`,
    steps: ['What you want to do', 'A model', 'This machine', 'Safety, first', 'Your first task'],
    goal: { local: 'Work on a project here', vps: 'Work on a server (VPS)', new: 'Build something new', wordpress: 'Look after a WordPress site' },
    goalHelp: {
      local: 'A folder on this computer.',
      vps: 'Over SSH - nothing is installed on the server.',
      new: 'A new app from a description.',
      wordpress: 'Safe deploys, backups, health and client approvals.',
    },
    modelHelp: 'SDC runs any model: a subscription you already have (Claude, ChatGPT, Gemini), an API key (DeepSeek, Qwen, Kimi…), or a free local model with Ollama.',
    connected: (count: number): string => `${count} provider(s) connected - you are ready.`,
    noneConnected: 'No model is connected yet.',
    openHub: 'Open the Provider Hub',
    doctorHelp: 'A quick look at this machine: git, node, the CLIs, the keychain.',
    runDoctor: 'Check this machine',
    safety: {
      timeMachine: 'Every change gets a checkpoint first. The Time Machine (Ctrl E) puts the folder back - one file or all of it.',
      contract: 'Before an AI starts, SDC shows what it understood - in your language - and waits for your yes.',
      kill: 'The Stop all button (Ctrl Shift .) stops every running turn, check, deploy and command at once.',
      demo: 'Try it: ask for a small change, then open the Time Machine and rewind it.',
    },
    firstTaskHelp: {
      local: 'Pick the folder you want to work on; SDC opens a chat in it.',
      vps: 'Add the server with its address; SDC checks its key before anything else.',
      new: 'Describe what you want built; SDC makes the folder and starts.',
      wordpress: 'Add the site: SDC reads wp-config.php for the database, and sets up backups and health.',
    },
    firstTask: { local: 'Open a folder', vps: 'Add a server', new: 'Start a new project', wordpress: 'Add the site' },
    skip: 'Skip',
    back: 'Back',
    next: 'Next',
  },
} as const;
